#!/usr/bin/env sh

manja_path() {
  case $1 in
    "h" )
      shift
      manja help "$*"
    ;;
    "i" )
      shift
      manja install "$*"
    ;;
    "u" )
      shift
      manja uninstall "$*"
    ;;
    * )
      shift
      echo 'Command not found! See help: '
      >&2 manja help "$*"
    ;;
  esac
}
manja_path "$*"

